# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

name: 1.1.$(Date:yyMM).$(build.buildId)

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job:
    steps:
    - task: NodeTool@0
      inputs:
       versionSpec: '14.x'
    - task: UseDotNet@2
      displayName: 'Use .NET Core 6.0.407 sdk'
      inputs:
       packageType: sdk
       version: 6.0.407
       installationPath: $(Agent.ToolsDirectory)/dotnet
       
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'

    - task: DotNetCoreCLI@2
      displayName: 'Build Keas.Mvc'
      inputs:
        command: 'build'
        projects: './Keas.Mvc/Keas.Mvc.csproj'
        arguments: '--configuration $(BuildConfiguration) /property:Version=$(build.buildNumber)'

    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './Keas.Mvc'

    - task: DotNetCoreCLI@2
      displayName: 'Run Server Tests'
      inputs:
        command: 'test'

    - task: Npm@1
      displayName: 'Run Client Tests'
      inputs:
        command: 'custom'
        workingDir: './Keas.Mvc/ClientApp'
        customCommand: 'run citest'

    - task: PublishTestResults@2
      displayName: 'Publish Client Tests'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/test-results.trx'
        testRunTitle: 'Client Tests'

- stage: Publish
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - job:
      steps:
        - task: NodeTool@0
          inputs:
           versionSpec: '14.x'
        - task: UseDotNet@2
          displayName: 'Use .NET Core 6.0.407 sdk'
          inputs:
           packageType: sdk
           version: 6.0.407
           installationPath: $(Agent.ToolsDirectory)/dotnet
        - task: DotNetCoreCLI@2
          displayName: 'Publish Keas.Mvc'
          inputs:
            command: 'publish'
            publishWebProjects: true
            zipAfterPublish: false
            modifyOutputPath: false
            projects: './Keas.Mvc/Keas.Mvc.csproj'
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/'

        - task: DotNetCoreCLI@2
          displayName: 'Publish Keas.Jobs.SendMail'
          inputs:
            command: 'publish'
            publishWebProjects: false
            zipAfterPublish: false
            projects: './Keas.Jobs.SendMail/Keas.Jobs.SendMail.csproj'
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/app_data/jobs/triggered'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
