CREATE TABLE [dbo].[Floor] (
    [Bldg_Key]            VARCHAR (150) NULL,
    [Floor_Key]           VARCHAR (150) NULL,
    [Floor_Code]          VARCHAR (150) NULL,
    [Floor_Name]          VARCHAR (150) NULL,
    [Floor_Order]         VARCHAR (150) NULL,
    [Basic_Gross]         VARCHAR (150) NULL,
    [CU_Gross]            VARCHAR (150) NULL,
    [Circulation]         VARCHAR (150) NULL,
    [Custodial]           VARCHAR (150) NULL,
    [Mechanical]          VARCHAR (150) NULL,
    [Parking]             VARCHAR (150) NULL,
    [Toilet]              VARCHAR (150) NULL,
    [NASF]                VARCHAR (150) NULL,
    [ASF]                 VARCHAR (150) NULL,
    [Space_Count]         VARCHAR (150) NULL,
    [Net_Usable]          VARCHAR (150) NULL,
    [Structural]          VARCHAR (150) NULL,
    [Outside_Gross]       VARCHAR (150) NULL,
    [Related_Gross]       VARCHAR (150) NULL,
    [Maintained_Gross]    VARCHAR (150) NULL,
    [Janitorized]         VARCHAR (150) NULL,
    [Above_Ground_Inches] VARCHAR (150) NULL
);

