import { IPersonInfo } from '../../models/People';

export const fakePeople: IPersonInfo[] = [
  {
    person: {
      id: 123,
      active: true,
      teamId: 10,
      user: null,
      userId: 'userid',
      firstName: 'Chuck',
      lastName: 'Yeager',
      name: 'Chuck Yeager',
      email: 'chuck@testpilot.gov',
      tags: null,
      title: null,
      homePhone: null,
      teamPhone: null,
      supervisorId: null,
      supervisor: null,
      startDate: null,
      endDate: null,
      category: null,
      notes: null,
      isSupervisor: true
    },
    id: 123,
    equipmentCount: 1,
    accessCount: 1,
    keyCount: 1,
    workstationCount: 0
  },
  {
    person: {
      id: 124,
      active: true,
      teamId: 10,
      user: null,
      userId: 'userid2',
      firstName: 'James',
      lastName: 'Kirk',
      name: 'James Kirk',
      email: 'capitan@trek.com',
      tags: null,
      title: null,
      homePhone: null,
      teamPhone: null,
      supervisorId: null,
      supervisor: null,
      startDate: null,
      endDate: null,
      category: null,
      notes: null,
      isSupervisor: false
    },
    id: 124,
    equipmentCount: 3,
    accessCount: 4,
    keyCount: 4,
    workstationCount: 2
  },
  {
    person: {
      id: 125,
      active: false,
      teamId: 10,
      user: null,
      userId: 'userid3',
      firstName: 'Bad',
      lastName: 'Zuy',
      name: 'Bad Zuy',
      email: 'inactive@test.com',
      tags: null,
      title: null,
      homePhone: null,
      teamPhone: null,
      supervisorId: null,
      supervisor: null,
      startDate: null,
      endDate: null,
      category: null,
      notes: null,
      isSupervisor: false
    },
    id: 125,
    equipmentCount: 3,
    accessCount: 4,
    keyCount: 4,
    workstationCount: 2
  },
  {
    person: {
      id: 126,
      active: true,
      teamId: 10,
      user: null,
      userId: 'userid4',
      firstName: 'Mike',
      lastName: 'Max',
      name: 'James Kirk',
      email: 'Max@test.com',
      tags: null,
      title: null,
      homePhone: null,
      teamPhone: null,
      supervisorId: null,
      supervisor: null,
      startDate: null,
      endDate: null,
      category: null,
      notes: null,
      isSupervisor: false
    },
    id: 126,
    equipmentCount: 3,
    accessCount: 4,
    keyCount: 4,
    workstationCount: 2
  }
];
