import { IEquipment } from 'ClientApp/models/Equipment';

export const fakeEquipment: IEquipment[] = [
  {
    type: 'Card',
    serialNumber: '4DVNPD2',
    make: 'Dell',
    model: 'OptiPlex 7040',
    protectionLevel: null,
    availabilityLevel: null,
    systemManagementId: null,
    space: null,
    equipmentAssignmentId: 2600,
    attributes: [
        {
          "id": 3675,
          "equipmentId": 24,
          "key": "wallKey",
          "value": "5"
        }
      ],
    assignment: {
      person: {
        id: 1249,
        active: true,
        teamId: 10,
        user: null,
        userId: 'eYeager',
        firstName: 'Eren',
        lastName: 'Yeager',
        name: 'Eren Yeager',
        email: 'eyeager@ucdavis.edu',
        tags: 'Student',
        title: null,
        homePhone: null,
        teamPhone: null,
        supervisorId: null,
        supervisor: null,
        startDate: null,
        endDate: null,
        category: null,
        notes: null,
        isSupervisor: false
      },
      id: 2600,
      equipment: null,
      equipmentId: 24,
      expiresAt: new Date('2022-01-16T07:08:34')
    },
    id: 24,
    name: 'Dell Desktop',
    notes: 'Monitor',
    tags: '',
    teamId: 10
  },
  {
    type: 'Card',
    serialNumber: '4DVNPD2',
    make: 'Hp',
    model: 'OptiPlex 9000',
    protectionLevel: null,
    availabilityLevel: null,
    systemManagementId: null,
    space: null,
    equipmentAssignmentId: 27,
    attributes: null,
    assignment: {
      person: {
        id: 1250,
        active: true,
        teamId: 10,
        user: null,
        userId: 'kKaneki',
        firstName: 'Ken',
        lastName: 'Kaneki',
        name: 'Ken Kaneki',
        email: 'kkaneki@ucdavis.edu',
        tags: 'Student',
        title: null,
        homePhone: null,
        teamPhone: null,
        supervisorId: null,
        supervisor: null,
        startDate: null,
        endDate: null,
        category: null,
        notes: null,
        isSupervisor: false
      },
      id: 27,
      equipment: null,
      equipmentId: 25,
      expiresAt: new Date('2022-01-16T07:08:34')
    },
    id: 25,
    name: 'Desktop',
    notes: 'hhh',
    tags: '',
    teamId: 10
  },
  {
    type: 'Card',
    serialNumber: '4DVNPD2',
    make: 'Samsung',
    model: 'OptiPlex 2340',
    protectionLevel: null,
    availabilityLevel: null,
    systemManagementId: null,
    space: null,
    equipmentAssignmentId: 28,
    attributes: null,
    assignment: {
      person: {
        id: 1251,
        active: true,
        teamId: 10,
        user: null,
        userId: 'eElric',
        firstName: 'Edward',
        lastName: 'Elric',
        name: 'Edward Elric',
        email: 'eelric@ucdavis.edu',
        tags: 'Student',
        title: null,
        homePhone: null,
        teamPhone: null,
        supervisorId: null,
        supervisor: null,
        startDate: null,
        endDate: null,
        category: null,
        notes: null,
        isSupervisor: false
      },
      id: 28,
      equipment: null,
      equipmentId: 26,
      expiresAt: new Date('2022-01-16T07:08:34')
    },
    id: 26,
    name: 'Desktop',
    notes: 'hhh',
    tags: '',
    teamId: 10
  },
  {
    type: 'Card',
    serialNumber: '4DVNPD2',
    make: 'Apple',
    model: 'OptiPlex 7120',
    protectionLevel: null,
    availabilityLevel: null,
    systemManagementId: null,
    space: null,
    equipmentAssignmentId: 27,
    attributes: null,
    assignment: {
      person: {
        id: 1252,
        active: true,
        teamId: 10,
        user: null,
        userId: 'aElric',
        firstName: 'Alphonese',
        lastName: 'Elric',
        name: 'Alphonse Elric',
        email: 'aElric@ucdavis.edu',
        tags: 'Student',
        title: null,
        homePhone: null,
        teamPhone: null,
        supervisorId: null,
        supervisor: null,
        startDate: null,
        endDate: null,
        category: null,
        notes: null,
        isSupervisor: false
      },
      id: 30,
      equipment: null,
      equipmentId: 28,
      expiresAt: new Date('2022-01-16T07:08:34')
    },
    id: 28,
    name: 'Desktop',
    notes: 'hhh',
    tags: '',
    teamId: 10
  }
];
